spring.application.name=nexfiscal
server.port=${SERVER_PORT:8080}
server.servlet.context-path=/api

spring.http.converters.preferred-json-mapper=jackson2

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.swagger-ui.use-root-path=true
server.forward-headers-strategy=framework
springdoc.swagger-ui.path=/swagger-ui.html

app.swagger.server-url=${APP_SWAGGER_SERVER_URL}
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES}
app.frontend.url=${FRONTEND_URL}

app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
